### ISSUE TITLE
Launch the ASP missile

### ISSUE THREAD

**Issue by kirkz47** [Frylovespi/History-of-Spaceflight#1]
As I leave the atmosphere the "flying" objective no longer shows as complete. It will be checked again as I re-enter the atmosphere. Hard to finish when you need to be "flying" above 100,000 m.

**Comment by Frylovespi** [comment]
Fixed for RSS version. If this is a stock bug issue, ASP has been removed from stock as have many other early missions.

**Comment by kirkz47** [comment]
Downloaded and installed new version and still having the same issue.

**Comment by Frylovespi** [comment]
Are you playing stock or RSS/RP-0 mod? The zip file contains the contract packs for both unmodded Stock and Real Solar System/ Realistic Progression-0 mods. Because, if you are playing RSS/RP-0 then 100,000m is not above the atmosphere. Works perfect in all my tests of RSS/RP-0. I launch my ASP it hits 100,000m and contract completes as normal. Also, this mission has been removed from the stock version of the game as of Version 0.5.5. So, if you are playing stock then make sure to delete the old install of the mod before installing the new copy. Sorry if I'm misunderstanding the situation.
